name: mystore
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  #flutter icon: ^2.0.0
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1
  modal_progress_hud_nsn: ^0.5.1
  image_picker: ^1.1.2
  marquee: ^2.2.3
  #multiple_images_picker: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
     - assets/images/


  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Black.ttf
        - asset: assets/fonts/SourceSansPro-Bold.ttf
        - asset: assets/fonts/SourceSansPro-BoldItalic.ttf
        - asset: assets/fonts/SourceSansPro-Light.ttf
        - asset: assets/fonts/SourceSansPro-ExtraLight.ttf
        - asset: assets/fonts/SourceSansPro-Semibold.ttf


